# Generated by Django 3.0.10 on 2020-09-21 05:10

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=200)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='freestuff.Category', verbose_name='Батьківська категорія')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Назва')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Розмір')),
                ('image', models.ImageField(blank=True, upload_to='things/%Y/%m/%d', verbose_name='Фото')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показати/сховати')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things', to='freestuff.Category')),
            ],
            options={
                'verbose_name': 'Річ',
                'verbose_name_plural': 'Речі',
                'ordering': ('name',),
                'index_together': {('id', 'name')},
            },
        ),
    ]
