# Generated by Django 3.0.10 on 2020-09-21 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freestuff', '0001_initial'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('first_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('last_name', models.CharField(max_length=50, verbose_name='І`мя')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField(verbose_name='Номер телефону')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адреса')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Індекс')),
                ('city', models.CharField(max_length=100, verbose_name='Місто/село')),
                ('shipping', models.CharField(blank=True, choices=[('Ukrposhta', 'Укрпошта'), ('NovaPoshta', 'Нова пошта')], max_length=20, null=True)),
                ('department', models.PositiveIntegerField(blank=True, null=True, verbose_name='відділення Нової пошти №')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updates', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.Coupon')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='freestuff.Things')),
            ],
        ),
    ]
